import { StockTicker } from '../src/HomeScreen';

export const stockTickers: StockTicker[] = [
  // Existing items
  {
    ticker: 'VFV',
    currencySymbol: '$',
    price: 222.45,
    currencyCode: 'CAD',
    performance: 0.05,
    description: 'Vanguard S&P 500 Index ETF',
  },
  {
    ticker: 'AAPL',
    currencySymbol: '$',
    price: 123.45,
    currencyCode: 'USD',
    performance: -0.05,
    description: 'Apple Inc.',
  },
  {
    ticker: 'GOOGL',
    currencySymbol: '$',
    price: 2345.67,
    currencyCode: 'USD',
    performance: 0.03,
    description: 'Alphabet Inc.',
  },
  {
    ticker: 'AMZN',
    currencySymbol: '$',
    price: 3456.78,
    currencyCode: 'USD',
    performance: 0.07,
    description: 'Amazon.com Inc.',
  },
  {
    ticker: 'MSFT',
    currencySymbol: '$',
    price: 456.78,
    currencyCode: 'USD',
    performance: 2.97,
    description: 'Microsoft Corporation',
  },
  // New items
  {
    ticker: 'FB',
    currencySymbol: '$',
    price: 356.78,
    currencyCode: 'USD',
    performance: 1.97,
    description: 'Facebook, Inc.',
  },
  {
    ticker: 'TSLA',
    currencySymbol: '$',
    price: 789.45,
    currencyCode: 'USD',
    performance: 3.45,
    description: 'Tesla, Inc.',
  },
  {
    ticker: 'NFLX',
    currencySymbol: '$',
    price: 543.21,
    currencyCode: 'USD',
    performance: -0.01,
    description: 'Netflix, Inc.',
  },
  {
    ticker: 'NVDA',
    currencySymbol: '$',
    price: 789.01,
    currencyCode: 'USD',
    performance: 0.15,
    description: 'NVIDIA Corporation',
  },
  {
    ticker: 'PYPL',
    currencySymbol: '$',
    price: 278.45,
    currencyCode: 'USD',
    performance: 0.05,
    description: 'PayPal Holdings, Inc.',
  },
  {
    ticker: 'BRK-A',
    currencySymbol: '$',
    price: 418000,
    currencyCode: 'USD',
    performance: 0.02,
    description: 'Berkshire Hathaway Inc.',
  },
  {
    ticker: 'V',
    currencySymbol: '$',
    price: 234.56,
    currencyCode: 'USD',
    performance: 0.03,
    description: 'Visa Inc.',
  },
  {
    ticker: 'JPM',
    currencySymbol: '$',
    price: 156.78,
    currencyCode: 'USD',
    performance: 0.01,
    description: 'JPMorgan Chase & Co.',
  },
  {
    ticker: 'JNJ',
    currencySymbol: '$',
    price: 178.9,
    currencyCode: 'USD',
    performance: -0.02,
    description: 'Johnson & Johnson',
  },
  {
    ticker: 'WMT',
    currencySymbol: '$',
    price: 139.45,
    currencyCode: 'USD',
    performance: 0.0,
    description: 'Walmart Inc.',
  },
  {
    ticker: 'PG',
    currencySymbol: '$',
    price: 138.67,
    currencyCode: 'USD',
    performance: 0.01,
    description: 'Procter & Gamble Co.',
  },
];
